### ISSUE TITLE
Read over this solution with Dexy

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/GitLab-Pages#1]
http://vanderveer.be/building-a-private-gh-pages-clone-with-dexy-and-gitlab/

**Comment by georgir** [comment]
That's too complex and weird. 
gh-pages is really simple... push to a special branch, it automagically gets served as static content at a special url, and that's that.
That link talks about markdown, templates, scripts, building... what? It may all be very cool and nice for certain cases, but I can not even begin to fish out the basic bits from it for the simple gh-pages use case.
