### ISSUE TITLE
bind localhost only

### ISSUE THREAD

**Issue by huglester** [Glavin001/GitLab-Pages#16]
Hello,

I have two ideas for now:
1) I think there somehow should be possibility, to bind to localhost only.
For example in my scenario, I have set up nginx proxy, like html.website.com; so I don't have port or something in the url.

I am not a nodejs guy, to solve these issues:)

Thank in advance!

**Comment by Glavin001** [comment]
Good ideas. Could you move the second idea into another issue. Thanks.

I think this is related to #12. I definitely want to make it support what you described above, with `nginx` proxy and a custom website domain without a port.

**Comment by huglester** [comment]
done :)

**Comment by Glavin001** [comment]
I am going to close this and consider it a duplicate of #12. Basically, we want `html.website.com` to map to this GitLab Pages server, and also not require additional port information.
