### ISSUE TITLE
How to install properly

### ISSUE THREAD

**Issue by DaAwesomeP** [Glavin001/GitLab-Pages#26]
First of all, thank you for creating this. I have been looking for something like this for a long time!
- Should I make a `gitlab_pages` user to run it?
- Where should I install it to (i.e. `/opt/gitlab_pages`)?
- Would you recommend installing a `system-ctl` service to automatically start it?
- I know that it's on the same server in which the repositories aren't actually encrypted in the first place, but can I use an `id_ecdsa` key?

**Comment by Glavin001** [comment]
> Should I make a gitlab_pages user to run it?

Up to you. Whatever user runs GitLab-Pages should have the appropriate tools installed (Node.js, Git, etc) and properly configured GitLab-Pages installation.

> Where should I install it to (i.e. /opt/gitlab_pages)?

Wherever you want to install it. 

I do hope to make GitLab-Pages a npm global install in the future such that you could install via `npm install -g gitlab-pages` instead.

> Would you recommend installing a system-ctl service to automatically start it?

If that is what you need. I usually just login to a remote server and start it manually. However, I do not have any critical usage of GitLab Pages right now.

Also take a look at https://www.npmjs.com/package/forever or other similar products for keeping the server running.

> I know that it's on the same server in which the repositories aren't actually encrypted in the first place, but can I use an id_ecdsa key?

I'd recommend trying it. Please post back here if you do or do not get it working.

**Comment by DaAwesomeP** [comment]
> I do hope to make GitLab-Pages a npm global install in the future such that you could install via npm install -g gitlab-pages instead.

This would be fantastic! Until then, my plan is to use PM2 (has system services integration and I've really liked using it in the past) with a separate user named `gitlab_pages` (for security) whose home folder is `/opt/gitlab_pages`. I'll install it to there and have Nginx pull from there. The separate user will also allow me to install RVM for that user alone (I don't plan to use Jekyll, but it;s nice to have it working).

**Comment by DaAwesomeP** [comment]
Reference to #24 for global support.
