### ISSUE TITLE
Error: Cannot find module '../build/Debug/nodegit.node'

### ISSUE THREAD

**Issue by WilldNY** [Glavin001/GitLab-Pages#31]
Hello, I installed docker-gitlab in the virtual machine, but when I'm in the project npm start when the following error:

`root@a-virtual-machine:/data/project/GitLab-Pages# npm start

> GitLab-Pages@0.1.0 start /data/project/GitLab-Pages
> node ./bin/www

module.js:327
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/project/GitLab-Pages/node_modules/nodegit/lib/nodegit.js:16:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.3.2
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! GitLab-Pages@0.1.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the GitLab-Pages@0.1.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the GitLab-Pages package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs GitLab-Pages
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls GitLab-Pages
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/project/GitLab-Pages/npm-debug.log`

sorry, my English is very general, through the google translation tool, please forgive

**Comment by WilldNY** [comment]
hello?

**Comment by Glavin001** [comment]
Looking at:

> /data/project/GitLab-Pages/node_modules/nodegit/lib/nodegit.js
> It sounds like the issue is with `nodegit`.

I recommend:
1. Running `npm install` again to ensure that all of the dependencies successfully were installed
2. Creating an Issue at https://github.com/nodegit/nodegit and asking for their help.

**Comment by WilldNY** [comment]
I'll go now and thank you for your help ! @Glavin001

**Comment by ryan-shaw** [comment]
@WilldNY @Glavin001 this issue can be closed.
